export enum SocketEventsEnum {
  REGISTER_JOIN_ROOM = "registerJoinRoom",
  REGISTER_STATUS = "REGISTER_STATUS",
  OTP_SENT = "otpSent",
  USER_LOGOUT = "userLogout",
  PATIENT_PROFILE = "PATIENT_PROFILE",
  JOIN_ROOM = "JOIN_ROOM",
  ROOM_JOINED = "ROOM_JOINED",
  APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED",
}
